### ISSUE TITLE
Error when trying to start / Readme inaccurate

### ISSUE THREAD

**Issue by tobilg** [henridf/apache-spark-node#1]
When I try to start I get the folllowing error:

```
ASSEMBLY_JAR=/Users/tobilg/Development/spark-1.5.2-bin-hadoop2.6/lib/spark-assembly-1.5.2-hadoop2.6.0.jar node_modules/apache-spark-node/bin/spark-node 
/Users/tobilg/WebstormProjects/Spark-Wrapper/node_modules/apache-spark-node/node_modules/java/lib/nodeJavaBridge.js:207
  var clazz = java.findClassSync(name); // TODO: change to Class.forName when classloader issue is resolved.
                   ^

Error: Could not create class org.apache.spark.deploy.NodeSparkSubmit
java.lang.NoClassDefFoundError: org/apache/spark/deploy/NodeSparkSubmit
Caused by: java.lang.ClassNotFoundException: org.apache.spark.deploy.NodeSparkSubmit
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

    at Error (native)
    at Java.java.import (/Users/tobilg/WebstormProjects/Spark-Wrapper/node_modules/apache-spark-node/node_modules/java/lib/nodeJavaBridge.js:207:20)
    at spark_parseArgs (/Users/tobilg/WebstormProjects/Spark-Wrapper/node_modules/apache-spark-node/lib/spark.js:21:38)
    at Object.sqlContext (/Users/tobilg/WebstormProjects/Spark-Wrapper/node_modules/apache-spark-node/lib/spark.js:33:5)
    at Object.<anonymous> (/Users/tobilg/WebstormProjects/Spark-Wrapper/node_modules/apache-spark-node/bin/spark-node:23:26)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

Furthermore, the https://github.com/henridf/apache-spark-node#running paragraph states that one should run `bin/node-spark`, which is non-existant.

**Comment by henridf** [comment]
Thanks for the report @tobilg

**Comment by tobilg** [comment]
Thanks for the super-fast fix! Will test it tomorrow.
